AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 900

Metadata:
  AWS::ServerlessRepo::Application:
    Name: rds-performance-insights-dump
    Description: rds-performance-insights-dump
    Author: Mitsuhiro Tanda
    SemanticVersion: 1.0.0
    ReadmeUrl: README.md

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rds-performance-insights-dump
      MemorySize: 256
      Runtime: go1.x
      Handler: rds-performance-insights-dump
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - pi:*
              Resource:
                - arn:aws:pi:*:*:metrics/rds/*
            - Effect: Allow
              Action:
                - rds:Describe*
              Resource:
                - "*"
        - S3CrudPolicy:
            BucketName: !Ref Bucket
      Events:
        HourlyGetResourceMetricsDump:
          Type: Schedule
          Properties:
            Schedule: cron(5 * * * ? *)
            Input: !Sub '{ "region": "${AWS::Region}", "interval": "1h", "dumpType": "GetResourceMetrics" }'
        HourlyDescribeDimensionKeysDump:
          Type: Schedule
          Properties:
            Schedule: cron(20 * * * ? *)
            Input: !Sub '{ "region": "${AWS::Region}", "interval": "1h", "dumpType": "DescribeDimensionKeys" }'
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub "rds-performance-insights-${AWS::AccountId}"

Outputs:
  Function:
    Description: "Function ARN"
    Value: !GetAtt Function.Arn
