AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 600

Metadata:
  AWS::ServerlessRepo::Application:
    Name: dump-rds-performance-insights
    Author: Mitsuhiro Tanda
    SemanticVersion: 1.0.0
    ReadmeUrl: README.md

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dump-rds-performance-insights
      MemorySize: 256
      Runtime: go1.x
      Handler: dump-rds-performance-insights
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - pi:*
              Resource:
                - arn:aws:pi:*:*:metrics/rds/*
            - Effect: Allow
              Action:
                - rds:Describe*
              Resource:
                - "*"
        - S3CrudPolicy:
            BucketName: !Ref Bucket
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub "rds-performance-insights-${AWS::AccountId}"

Outputs:
  Function:
    Description: "Function ARN"
    Value: !GetAtt Function.Arn
